all: main main2 main3

main: main.o
	g++ -o main main.o

main.o: main.cpp
	g++ -c main.cpp

main2: main2.o
	g++ -o main2 main2.o

main2.o: main2.cpp
	g++ -c main2.cpp

main3: main3.o
	g++ -o main3 main3.o

main3.o: main3.cpp
	g++ -c main3.cpp

